name: lumovies
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider:
  cached_network_image: ^3.3.0
  lottie:
  icon_broken:
  flutter_smart_dialog: ^4.9.4
  freezed_annotation: ^2.4.1
  flutter_dotenv: ^5.1.0
  carousel_slider:
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  dependency_validator:


flutter:
  uses-material-design: true
  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee/ABeeZee-Regular.ttf
        - asset: assets/fonts/ABeeZee/ABeeZee-Italic.ttf



  assets:
    - assets/lottie/
    - assets/
    - .env
