name: lumovies
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider:
  cached_network_image: ^3.3.0
  shared_preferences:
  dartz:
  lottie:
  change_app_package_name: ^1.1.0
  icon_broken:
  connectivity_plus:
  flutter_smart_dialog: ^4.9.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_reflectable: ^1.0.1
  icons_plus:
  insta_image_viewer: ^1.0.2
  flutter_dotenv: ^5.1.0
  carousel_slider:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  dependency_validator:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_2.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee/ABeeZee-Regular.ttf
        - asset: assets/fonts/ABeeZee/ABeeZee-Italic.ttf



  assets:
    - assets/lottie/
    - assets/images/
    - assets/
    - .env
